[package]
name = "powdr"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "^4.1", features = ["derive"] }
codespan-reporting = "^0.11"
itertools = "^0.10"
json = "^0.12"
lalrpop-util = {version = "^0.19", features = ["lexer"]}
lazy_static = "^1.4.0"
mktemp = "0.5.0"
num-bigint = "^0.4"
polyexen = { git = "https://github.com/Dhole/polyexen", rev="c4864d2debf9ae21138c9d67a99c93c3362df19b"}
halo2_proofs = "0.2"
prettytable = "0.10.0"
num-traits = "0.2.15"
num-integer = "0.1.45"
regex = "^1.7.0"
parking_lot = "0.12"

[build-dependencies]
lalrpop = "^0.19"

[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { git ="https://github.com/ed255/halo2", rev = "63e969673de83a410f21553fabec8f4b35bda1a5" }

[patch.crates-io]
halo2_proofs = { git ="https://github.com/ed255/halo2", rev = "63e969673de83a410f21553fabec8f4b35bda1a5" }
